# Generated by Django 4.1.2 on 2022-10-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userextension_address_userextension_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
