# Generated by Django 4.1.2 on 2022-10-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userextension_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
