# Generated by Django 4.1.2 on 2022-10-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userextension_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
