# Generated by Django 4.1.1 on 2022-10-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='mascota',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
