# Generated by Django 4.1.2 on 2022-10-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_persona_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('brief_description', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
    ]
