# Generated by Django 4.1.2 on 2022-10-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_posts_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='featured',
        ),
    ]
