# Generated by Django 4.1.2 on 2022-10-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_posts_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
    ]
