# Generated by Django 4.1.2 on 2022-10-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='edited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
