# Generated by Django 4.1.2 on 2022-10-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_posts_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
