# Generated by Django 4.1.2 on 2022-10-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='edited',
        ),
    ]
