# Generated by Django 4.1.2 on 2022-10-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_posts_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_avatar',
        ),
    ]
