# Generated by Django 4.1.2 on 2022-10-28 21:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_posts_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
    ]
