# Generated by Django 4.1.2 on 2022-10-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_posts_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='subtitle',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
