# Generated by Django 4.1.2 on 2022-10-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_posts_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='subtitle',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
